   name: Upload Images to Lokalise

   on:
     push:
       paths:
         - 'images/**' # Monitor the 'images' folder for new image files

   jobs:
     upload:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout repository
           uses: actions/checkout@v2

         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '14'
           
         - name: Install dependencies
           run: npm install

         - name: Upload images to Lokalise
           env:
             LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
           run: |
             node .github/scripts/upload_images.js
